# Methods

## SURVEY DESIGN

Methodology for the `r yr` sablefish  research and assessment surveys employed a stratified random sampling (StRS) design.  The survey protocol required the StRS component to be completed from the southern end of Vancouver Island to the north coast of Haida Gwaii. The survey design was modified in 2020 in response to the COVID-19 pandemic.  The length of the trip was reduced by removing the traditional inlet component of the survey.

### STRATIFIED RANDOM SAMPLING SURVEY DESIGN COMPONENT

Since 2011, the StRS design has been conducted in all offshore survey areas. The StRS design began in 2003 with the purpose of distributing tag releases at random, collecting biological samples and developing a catch-rate based index of abundance [@Wyeth2003]. It also provided an alternative design to the historic traditional offshore component of the survey (1990 to 2010) which occured at fixed locations. 

Under the StRS design the offshore survey area is partitioned into five spatial strata (S~1~ to S~5~) and three depth strata (RD~1~ to RD~3~) for a total of 15 (Figure \@ref(fig:figure1)). The five spatial strata are S~1~ (South West Coast Vancouver Island or SWCVI), S~2~ (North West Coast Vancouver Island or NWCVI), S~3~ (Queen Charlotte Sound or QCS), S~4~ (South West Coast of Haida Gwaii or SWCHG), and S~5~ (North West Coast of Haida Gwaii or NWCHG).  The three targeted depth ranges are 100-250 fathoms (RD~1~), 250-450 fathoms (RD~2~), and 450-750 fathoms(RD~3~). The area within each of the 15 strata are sectioned into 2 km x  2 km grid cells or ‘fishing blocks’ from which set locations are randomly chosen. 

From 2003 through 2005, five grid cells were randomly selected in each spatial-depth stratum. From 2006 through 2010, the number was increased to six. An analysis was completed for the 2011 survey to optimize the allocation of the blocks to strata for the 2011 and 2012 survey. However, in order to lower survey costs, the number of blocks were further reduced for the 2013 survey, from a total of 110 to 91 offshore blocks while maintaining the same relative allocation of blocks to strata. This total number of blocks has been in place on all subsequent surveys (Table \@ref(tab:table1)), including `r yr` (Figure \@ref(fig:figure2)).

## VESSELS

The `r yr` survey of `r setcnt` sets was chartered aboard the 25.34 meter F/V `r boat` (Figure \@ref(fig:figure3)), skippered by `r captain`  between `r dates`, `r yr` (Appendix \@ref(app:first-appendix)). Information about the vessel can be found at [\underline{http://marinetraffic.com}](http://marinetraffic.com). 

## FISHING GEAR

The longline trap gear consisted of a groundline resting on the ocean floor with 25 baited traps attached to beckets at 150 foot intervals along its length and 90 pound anchors at each end (Figure \@ref(fig:figure4), b). A flagpole was required for at least one end of the set to improve visibility for retrieval. The traps  were steel frame with a bottom hoop diameter of 54 inches and covered with an North American #84 black braided nylon web of 2.75 inch mesh (Figure \@ref(fig:figure4), a). The tunnels were made of green braided, knotless, 1.25 inch mesh. The traps did not include escape rings; but instead a ‘rot panel’  of # 21 cotton located above the middle ring. 

Standard bait bags (6 by 12 inches) made of 1/8 inch web with a nylon drawstring and #7 stainless trolling snaps were included with the traps. 

## FISHING OPERATIONS

During normal survey fishing operations gear was deployed on alternate days. Prior to deployment, the Fishing Master inspected the block to determine fishability and if it was within the targeted depth range.  The goal was to have as much gear as possible within the block boundaries.  If unfishable, the survey protocol requires that an alternate block is to be chosen to the east, west, north, and south, respectively. If none of those blocks meet the criteria, an alternate block of the same area and depth strata was randomly chosen.  In 2020, the choice of alternate blocks were limited to a pre-selected list prepared by DFO in advance of the survey.  Additionally, the crew size was reduced to three and all data collected during fishing operations were recorded on paper forms, rather than electronically.

Two science staff recorded information associated with the deployment of the gear. One science member was positioned in the wheelhouse and recorded set details on the bridge log data form. The start and end geo-referenced positions of each set were entered at the time when the first and last traps were set over the stern. Depths were recorded at one-minute intervals between the first and last anchors being set. Later, the duration of the set was calculated as the time elapsed between the first anchor being set over the stern and the first anchor hauled aboard (Appendix \@ref(app:second-appendix), Figure B.1).

A set log was filled out on the deck by the science recorder who had maximum visibility of the crew setting the traps over the stern rail. The set log included the time and identity of the first and last buoys, anchor time, a tally of beckets and traps, as well as the unique identifying numbers of sensors deployed (Appendix \@ref(app:second-appendix), Figure B. 2)

### Stratified Random Component (StRS)

Sets in StRS blocks had a targeted soak time of 24 hours.  Fishing sets were designated useable if hauled between 22 and 26 hours. Traps were baited with 10 pounds of loose offshore Pacific Hake (*Merluccius productus*) and 2 pounds of bagged squid.

## CATCH PROCESSING

Haulback speed allowed the science crew to accurately record catch. One science and one crew member were positioned on deck at the haul card station; the science staff recorded the catch and the crew member managed the movement of baskets. As the groundline was hauled, each becket and trap were entered in the charter catch log form (Appendix \@ref(app:second-appendix), Figure B.3). Crew members alerted the recorder about any damage to a trap (i.e. holes) which was then recorded.

Catch by species from each trap was sorted into baskets by the crew. Baskets were then weighed to the nearest 0.2 kg on a motion compensating scale and given a basket use code of D, A, T, L, SD or F.  Code D designated fish species as discards or commercial catch; code A allocated sablefish for age samples; code T allocated sablefish to be tagged and released; code L allocated fish for length samples; code SD identified sublegal sablefish discards; code F represented fish frames with amphipod or hagfish damage (Appendix \@ref(app:second-appendix), Figure B.3).   The next day, the entries on charter catch log form were transposed to tabular format on the charter catch log entry form (Appendix \@ref(app:second-appendix), Figure B.4).

### Sablefish Allocation Details
 
Prior to 2018, sablefish were tagged from 1/3 of the traps on StRS sets and 1/2 of the traps on the inlet sets. Due to high catch numbers, the survey protocol was revised in 2018 to designate ~125 sablefish to be tagged (T) from 1/3 of the traps on all sets.  When catches were high, traps targeted for tagging were spread throughout the string to avoid tagging the first 125 fish.  A biological sample was collected from the coded "A" traps with the goal of selecting 50 to 60 fish.  If CPUE was high, the new survey protocol of 2018 designated a minimal of two traps to be used for samples.  If both traps contained more than 60 sablefish, a random process was used to select ~60 specimens.

The remaining traps were allocated to the discard category and sorted by size into either legal (D) or sublegal (SD) discards. The SD (sublegal discards) code was added during the 2017 survey to account for the large numbers of juvenile sablefish and facilitate their quick return to the ocean. Legal discards (D) of sablefish were kept by the vessel and processed as commercial catch. 

## BIOLOGICAL SAMPLING (LWSMO)

Biological samples were collected from sablefish and rougheye/blackspotted rockfish (*Sebastes aleutianus/Sebastes melanostictus*) specimens. Measurements were recorded for fork length (L), body weight (W), sex (S) and maturity level (M) (Appendix \@ref(app:second-appendix), Figure B.5). Sagittal otoliths (O) were collected and stored for potential ageing by the sclerochronology laboratory.  In addition, tissue for DNA was collected from the rougheye/blackspotted rockfish complex for later species determination.  Since this complex of two distinct species [@Orr2008] have similar appearances with slight variations in colour markings and dorsal fin lengths, the sampler visually identifed each specimen as either a rougheye, a blackspotted or a hybrid species.  All rockfish and legal-sized sablefish (fork length > 55 cm) that were sacrificed for biological samples were dressed, frozen, and landed as commercial catch.

## SABLEFISH TAGGING

Fish destined to be tagged were transferred from the sorting area to a tagging tank.  A vessel crew member was positioned to retrieve sablefish from the tank and provide assistance with fish handling.  A scientist stood at the sample station and tagged fish with a Mark II Long Tagging gun loaded with Floy FD-94 T-bar anchor tags.  The tag was inserted on the left side of the fish, 1 cm below and 2-3 cm behind the anterior insertion of the first dorsal fin.  Fork length (mm) measurements were taken. Before release, any sampling errors, injuries or damage to the fish were recorded on the tagging form by a second scientist. Tag checks were performed systematically to ensure tag numbers on the data form matched those on the fish specimen (Appendix \@ref(app:third-appendix), Figure B.6).

## SABLEFISH TAG RECOVERY

Any previously tagged fish brought aboard may have been treated in one of two ways.  First, sablefish with Canadian tags were re-released with a new tag and the previous tag was removed. In addition, any wounds from the old tag were recorded.  Second, sablefish with a foreign agency tag or sablefish that had sustained numerous injuries were retained for biological sampling.  For these specimens, the tag and otoliths were stored in a bar-coded vial that was later scanned into the GFBioField Tag Recovery Entry form by DFO staff [@Olsen2010]. Foreign tags were returned to their country of origin.

During survey years 1992 through 1997 and 2004, previously tagged sablefish were re-released with the same tag. New tagging protocols of replacing the tag began in 2005.



```{r SensorText, echo=FALSE}
   # -- determine the sets that deployed SBE and HOBO and CTD
   sense  <-  paste("select Year, SUM(SBE39) AS SBE39, SUM(HOBO) AS HOBO, ",
                    "SUM(CTD) AS CTD, SUM(CAM) AS CAM ",
                    "from dbo.Report_SBE_HOBO_IND ",
                    "group by Year having (Year =", yr,")", sep="")
   #sensor  <-  GetSQLData(sense,"Sablefish")
   #write.table(sensor, file = paste(path,"methods01.csv",sep=''),row.names=FALSE, na="",col.names=TRUE,  sep=",") 
   sensor <-  read.csv(paste(path,'methods01.csv',sep=''), header=T)
   
```

## OCEANOGRAPHIC SENSOR DATA COLLECTION

A Sea-bird Bird SBE 39 temperature and pressure logger was placed in a protective plastic pipe and attached to the middle trap on the string of gear. Data was successfully collected from `r sensor[1,2]` sets in `r yr` (Appendix \@ref(app:third-appendix)).  A SBE 39 was also placed in the tagging tank on hauling days to record water temperature.   Data from the SBE temperature and pressure loggers were processed at sea after the set was complete. 

## ELECTRONIC MONITORING VIDEO DATA COLLECTION  

During haulback, the electronic monitoring (EM) system cameras were activated by the hydraulic sensor.  Three standard analog cameras were positioned at optimal viewing angles to record survey activities.  Two cameras were stationed along the mast to record the catch as it was processed at the hopper. A third camera was stationed on the side of the wheelhouse to record the traps as they were brought over the rail. The video data from each set was reviewed by science staff the following day to provide quality control on catch data.

\clearpage
